return {
	"maskudo/devdocs.nvim",
	lazy = false,
	dependencies = {
		"folke/snacks.nvim",
	},
	cmd = { "DevDocs" },
	keys = {
		{
			"<leader>io",
			mode = "n",
			"<cmd>DevDocs get<cr>",
			desc = "Get Devdocs",
		},
		{
			"<leader>ii",
			mode = "n",
			"<cmd>DevDocs install<cr>",
			desc = "Install Devdocs",
		},
		{
			"<leader>id",
			mode = "n",
			"<cmd>DevDocs delete<cr>",
			desc = "Delete Devdoc",
		},
	},
	opts = {
		ensure_installed = {
			"zsh",
			"go",
			"html",
			"http",
			"css",
			"javascript",
			"typescript",
			"c",
			"cpp",
			"docker",
			"lua~5.1",
			"react",
			"postgresql~18",
			"react_router",
			"react_native",
			"openjdk~25",
			"python~3.13",
			"pygame",
			"numpy~2.4",
			"pandas~2",
			"cmake",
			"django~6.0",
			"flask",
			"gtk~4.0",
			"qt~6.9",
			"matplotlib",
			"nextjs",
		},
	},
}
